
name: Issue Report
description: File a bug report
title: "[issue]: "
assignees:
  - JoakimMellonn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: issue-description
    attributes:
      label: Please describe your issue.
      description: While being concise and descriptive, if applicable use code snippets.
      placeholder: The issue is...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform is the issue happening on?
      multiple: true
      options:
        - Mobile (iOS)
        - Mobile (Android)
        - Chromium based browser
        - Safari
        - Firefox
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
